pipeline {
    agent any

    stages {
        stage('Clone Repository'){
            steps{
                checkout([$class: 'GitSCM', 
                branches : [[name: '*/main']], 
                userRemoteConfigs: [[url: 'https://github.com/TastyBiscuit0808/PES2UG21CS098_Jenkins.git']]
                ])
            }
        }
        stage('Build') {
            steps {
                build 'PES2UG21CS098-1'
                sh 'g++ main.cpp -o output'
                // Add build commands here
            }
        }
        stage('Test') {
            steps {
                sh './output'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploy'
                // Add deployment commands here
            }
        }
    }

    post {
        failure {
            echo 'Pipeline failed'
        }
    }
}
